version: '3'

networks:
    news_aggregator_network:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - news_aggregator_network
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis
        ports:
            - "9001:9000"
        networks:
            - news_aggregator_network

    mysql:
        image: mysql:latest
        container_name: ${APP_NAME}_mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "33360:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - news_aggregator_network

    redis:
        image: redis:latest
        container_name: ${APP_NAME}_redis
        ports:
            - "63790:6379"
        volumes:
            - ./data/redis:/data
        networks:
            - news_aggregator_network
